language: node_js

sudo: required

node_js:
  - "0.10.32"

services:
  - docker

before_install:
  - sudo apt-get install -y make
  - make test-image deps

env:
  - GROUP=weaveworksdemos COMMIT=$TRAVIS_COMMIT TAG=$TRAVIS_TAG REPO=front-end;

script:
  - make test

after_success:
  - set -e
  - if [ -z "$DOCKER_PASS" ]; then echo "Build triggered by external PR. Skipping docker push" && exit 0; fi
  - docker login -u $DOCKER_USER -p $DOCKER_PASS;
  - ./scripts/build.sh
  - ./test/container.sh
  - ./scripts/push.sh

before_deploy:
  - openssl aes-256-cbc -K $encrypted_a10f349f39af_key -iv $encrypted_a10f349f39af_iv
    -in front-end_deploy_rsa.enc -out front-end_deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 $TRAVIS_BUILD_DIR/${REPO}_deploy_rsa
  - ssh-add $TRAVIS_BUILD_DIR/${REPO}_deploy_rsa
addons:
  ssh_known_hosts: $BASTION
deploy:
  provider: script
  skip_cleanup: true
  # The deploy.sh file points to the deploy file on the bastion. Not one in the repo.
  script: ssh -o StrictHostKeyChecking=no $BASTION_USER@$BASTION ./deploy.sh ${REPO} $COMMIT
  on:
    branch: master
notifications:
  slack:
    secure: oMZjbI7Kp3+6pN+prw/I4vw3UyOiY/XURPqzCnwhgZROwhCUubO9esl575qTFt1pDUKf1/1UOjLEY/2yZKHEWye8x5ilmU6iBT3PmQ80WLvi0jdgMIhhOTaIyA9HTyLx98XHWpDEDdsXdVhJ9yM+YN6V0zlftvsP2PToYebw/ob2HU5twuChSC+/rcXFbEL7cW+0y6EbjWJnqbb6TLv5Le+uVz8FpIAoHRLal8LqhxYU2csuXYU0oK6uZxFRDcPiLEEELc9inHsTAH9svhpiqFw8le7eWAwn10XOuUAPKxWmnOOcQFvRnD8kO4SIBbk/y1YZQL32uSKqQcRTDOb43I21DIE5j0FxfAo5LiIWxOtMCn3DCP9RDDoMMAVnUJM8uZMOBtMWcfMGVr3mRAKNzz66Fhv2AFbXxE0Zu8NksL1adXE0ld4QqdszAwA0j05hGmrydaJs5ZS+PV2QVeYkXeNCxWkRyGobfUg9l+9aybfU5uH7KCvJtG7eEmyVIv6qy/iLcP3lgCHIegtUZt6eKh2QtLPRAC6T64u7fixpHkbFkEhvVhpyuzs5BN1wTwORyg4q8jyuG6cL1W3gutazQPZwD5wZGi9pkFRKsUmpiARSP095yjv+4mwdWT41/40tURuMsARLhdmkpuox0WVEE7qbfLMt18xHkGSLxTtsA2s=
